ZENDESK_API_TOKEN = 'your_zendesk_api_token'
ZENDESK_EMAIL = 'your_zendesk_email'
ZENDESK_SUBDOMAIN = 'your_zendesk_subdomain'
OPENAI_API_KEY = 'your_openai_api_key'
DATABASE_URL = 'your_database_url'
JWT_SECRET = 'your_jwt_secret_key'